### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by cvandermeer** [seuros/capistrano-sidekiq#119]
if i set pty to false i get this error

sudo: no tty present and no askpass program specified

**Comment by cvandermeer** [comment]
This seemed to be an issue with my server configuration

**Comment by stefanosc** [comment]
@cvandermeer could you share how you fixed the issue?
I had exactly the same issue and setting pty to true didn't make it work (it prompted for password but then got stuck)
At the moment I set my deploy user as:
```
deploy         ALL=(ALL)       NOPASSWD: ALL
```

But that is less than ideal.
I would appreciate knowing if you found any other solution that worked for you.

Thank you!

**Comment by stefanosc** [comment]
@seuros I am also having this issue, and tried many of the suggestions shared on stackoverflow or the cap google groups... Including commenting out `#Defaults    requiretty` in /etc/sudoers.
I would really appreciate if you could share any suggestions on anything else to do to fix / debug this issue. thank you!

**Comment by stefanosc** [comment]
@cvandermeer @seuros could you share anything?
Thank you!

**Comment by Sathors** [comment]
Hi @stefanosc, in case you or someone else is still unsure about this, I would recommend putting the following line in your sudoers file:
`deploy         ALL= NOPASSWD: /usr/bin/monit`

This gives permissions to the deploy user only to the monit command (without a password prompt), hence preventing privileges escalation (or at least making it MUCH harder).
For the moving of the template.conf file (the sidekiq:monit:config task), do it yourself by hand, so that the deploy user does not have to do it.

**Comment by stefanosc** [comment]
Hello @Sathors this is actually what I ended up doing.
In case anyone else lands here, I found the following capistrano guide on topic useful:
http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/#toc_8
