### ISSUE TITLE
Sidekiq process with scheduled jobs does not die?

### ISSUE THREAD

**Issue by phillbaker** [seuros/capistrano-sidekiq#15]
I'm running sidekiq on several setups, but seeing that sidekiq processes consistently do not die on a machine that has lots of "scheduled jobs" (ie jobs scheduled to be performed at a future date via `perform_in`).

Seen in the `sidekiq.log`:

```
2014-04-15T21:47:16Z [pid] ... DEBUG: Terminating 4 actors...
...
2014-04-15T21:47:26Z [pid] ... ERROR: Couldn't cleanly terminate all actors in 10 seconds!
```

This means that after most deploys we end up killing old sidekiq processes by hand, otherwise we get tons of sidekiq processes and unicorns get slow. (But the processes do respond nicely to a `kill` command.)

Is this an issue with `sidekiq-ctrl` not responding to the `kill -0` command while it has scheduled jobs or something in the capinstrano integration?

**Comment by snovity** [comment]
I'm a little bit late to the party, just wanted to share my thoughts.

Instead of unmonitoring I chose to completely stop monit during deploy, and start it after the deploy is done. The thing is, I wanted to be always sure, that monit is monitoring the processes, so I've setup an outside service like Pingdom to monitor the web page of my monit. With unmonitoring approach, there is a chance, that monit will be running, but will not be monitoring anything.  For instance if deploy fails.

Btw I've added a hook
```ruby
after :failed, :monitor_all
```
That would start monit back when deploy fails, it seems that there is no such hook in `monit.rake`.
