### ISSUE TITLE
Is is safe/smart to use capistrano-sidekiq?

### ISSUE THREAD

**Issue by Inza** [seuros/capistrano-sidekiq#222]
Hello guys, I love the job you have done with capistrano-sidekiq! ;) But recently, I have run across this article: https://binarapps.com/blog/why-you-should-avoid-using-capistrano-sidekiq/ :-/

What do you think about thoughts in it? Do you plan to add support for systemd, etc to capistrano-sidekiq? I would love to use this "easy to use" solution to get sidekiq running in production (which capistrano-sidekiq is). But many arguments in that article do concern me. On the other hand, I do not think that sidekiq is a dead end path. Instead, it might be evolved to fix the issues mentioned in those concerns? Do you understand them as issues as well?

Let me know your ideas and plans, please.

And thanks a lot for your awesome gem ;). Even with some issues, it is still a very good work!

**Comment by seuros** [comment]
Hi @Inza .

Thank you for pointing about about the article. 
The [systemd](https://github.com/seuros/capistrano-sidekiq/blob/master/README.md#integration-with-upstart) and [upstartd](https://github.com/seuros/capistrano-sidekiq/blob/master/README.md#integration-with-systemd) integrations were merged and released weeks before the article was authored which make the blog just a Buzzfeed-like article. They could have spend time to contribute to the solution instead of writing that article to complain.

if you think that answer your question, fell free to close this issue.

**Comment by Inza** [comment]
Hello @seuros, thanks for the clarification. Hence it is both safe and smart to use capistrano-sidekiq :-) Thanks!
