### ISSUE TITLE
Not started sidekiq after deploy - if pty is true

### ISSUE THREAD

**Issue by kjakub** [seuros/capistrano-sidekiq#23]
*\* comment is not valid - REMOVED by author

**Comment by baweaver** [comment]
Have you tried just adding a ``nohup`` to it with a ``sleep 1`` to make sure the process forks? That's probably your issue is that an interactive shell is going to hang up before the process forks and daemonizes. It's been fairly common in the wild:

* https://github.com/fabric/fabric/issues/395
* https://github.com/sshingler/capistrano-resque/issues/91
* https://github.com/sshingler/capistrano-resque/pull/96

Can we see about testing that as an option when ``pty == true``

**Comment by vizcay** [comment]
I've been recently bitted by this same issue and I didn't wanted to remove the pty setting because I was pretty sure it was there because of something. Because I was writting manualy my task I just added **&& sleep 2** to the end of it to allow the process to fork before capistrano disconnects (found the explanation here: http://blog.hartshorne.net/2013/03/capistrano-nohup-and-sleep.html)

```
  desc "Start sidekiq"
  task :start do
    run "cd #{current_path} && bundle exec sidekiq --environment production --daemon --config config/sidekiq.yml && sleep 1"
  end
```

**Comment by rahulmurkute-tudip** [comment]
I tried with setting pty to false and add these  " sleep 2"  while creating the daemon.
But it still get disappear
