### ISSUE TITLE
Run different queues on each role / server

### ISSUE THREAD

**Issue by RobinClowers** [seuros/capistrano-sidekiq#84]
I want to run a queue on my web server for some jobs and other jobs on a utility server. It doesn't look like this is possible right now, how would feel about me implementing that functionality in a similar way to specifying processes per role?

**Comment by jsantos** [comment]
I usually do this by specifying different configuration files per role, each configuration file contains the queues for which the role is responsible.

**Comment by metavida** [comment]
I recently opened Pull #141 which adds some new config syntaxes that I think might help in your case:

```ruby
set :sidekiq_role, [:web, :util]
set :sidekiq_web_queue, :web
set :sidekiq_util_queue, [:util, :misc]
```

FWIW, I agree with @jsantos that it's usually better to store config options (like which queues to use) within a config file. @jsantos I'm curious as to the syntax you use with the current gem to specify per-role config files for sidekiq. With my pull request the syntax would be like this:

```ruby
set :sidekiq_role, [:web, :util]
set :sidekiq_web_config, 'conf/sidekiq/web.yml'
set :sidekiq_util_config, 'conf/sidekiq/util.yml'
```

**Comment by RobinClowers** [comment]
@metavida That's the same syntax I added in https://github.com/seuros/capistrano-sidekiq/pull/85, hopefully yours will get merged. :game_die:

**Comment by metavida** [comment]
Thanks for the heads up, @RobinClowers! Apparently I did a relatively poor job of researching existing pulls (Pull #81 has some overlap too!) :frowning: 

FWIW, Pull #141 lets you specify *any* config attribute on a per-role basis (e.g. `:sidekiq_util_log`, `:sidekiq_web_tag`, etc). Fingers crossed that that gives it a leg up on the review process, though perhaps because it changes more it'll make it harder to review with confidence too.

**Comment by AlexanderFisenko** [comment]
Did they finally add this functionality?
