### ISSUE TITLE
Solution to setting environment variables

### ISSUE THREAD

**Issue by EmergeIncRailsCasts** [seuros/capistrano-sidekiq#92]
I'm looking for a solution to set some environmental variables prior to sidekiq starting.

I've tried using `dotenv` but it didn't pick up my `.env` or `.env.production` file.
I've tried adding my ENV (source of all my variables) to my `$HOME/.profile` and it still didn't pick up those.

I've been testing by reading /proc/$PID/environ

Ideally I don't want to keep my sensitive data in `deploy.rb` file or inside my repo.

Any ideas?

**Comment by EmergeIncRailsCasts** [comment]
Okay, figured it out. `dotenv` was installed in :development, :test groups.  Adding it to :production group made it work.

**Comment by seuros** [comment]
if you use rbenv, you don't need that gem. You can use rbenv-vars, there is similar files for rvm.

**Comment by hbin** [comment]
@seuros Well, `rbenv-vars` does. But `.env` file is a more common place to put local environment variables. Since all **Procfile-based** projects respect to `.env`.

**Comment by hbin** [comment]
Same issue https://github.com/bkeepers/dotenv/issues/134

**Comment by Sathors** [comment]
Somebody has any news on this?
It seems  that sidekiq does not get access to the .env* variables. I have access to them in a rails console, but not in sidekiq.

**Comment by Sathors** [comment]
Actually, when I use exactly the same command than the one used by capistrano to execute sidekiq, from inside the current/ directory, it works fine.
When run by the capistrano-sidekiq gem, it does not find the dotenv variables.

Would it be related to bkeepers/dotenv/issues/134?
I don't understand how it could be different, because normally the command should be run in the 'current' directory by capistrano, isn't it?
